services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - DOTNET_IMAGE_VERSION=${DOTNET_IMAGE_VERSION}
                - DOTNET_TIME_ZONE=${DOTNET_TIME_ZONE}
                - DOTNET_LANG_NAME=${DOTNET_LANG_NAME}
                - DOTNET_LANG_INPUTFILE=${DOTNET_LANG_INPUTFILE}
                - DOTNET_LANG_CHARMAP=${DOTNET_LANG_CHARMAP}
                - DEBIAN_FRONTEND=${DOTNET_DEBIAN_FRONTEND}
        image: ${CONTAINER_AUTHOR}/${PROJECT_NAME}/dotnet:${DOTNET_IMAGE_VERSION}
        container_name: ${PROJECT_NAME}_web
        env_file:
            - ${ENV_FILE_PATH}
        environment:
            - DOTNET_LANG_NAME=${DOTNET_LANG_NAME}
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        ports:
            - ${DOTNET_HTTP_EXPOSE_PORT}:${DOTNET_HTTP_INNER_PORT}
            - ${DOTNET_HTTPS_EXPOSE_PORT}:${DOTNET_HTTPS_INNER_PORT}
        # expose:
        #     - ${DOTNET_HTTP_INNER_PORT}
        #     - ${DOTNET_HTTPS_INNER_PORT}
        volumes:
            - ./certs/dotnet/BestStore.pfx:/deploy/BestStoreMVC/https/BestStore.pfx:ro
        networks:
            beststoremvc_net:
                ipv4_address: ${DOTNET_HOST_IP}
        tty: true
        restart: always

networks:
    beststoremvc_net:
        driver: bridge
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
                  gateway: ${NETWORK_GATEWAY}