# 測試 Docker 建置工作流程
name: Test Docker Build

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    test-docker-build:
        name: Test Docker Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image (without push)
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  tags: test/beststore:latest
                  push: false
                  build-args: |
                      DOTNET_IMAGE_VERSION=8
                      DOTNET_TIME_ZONE=Asia/Taipei
                      DOTNET_LANG_NAME=zh_TW.UTF-8
                      DOTNET_LANG_INPUTFILE=zh_TW
                      DOTNET_LANG_CHARMAP=UTF-8
                      DEBIAN_FRONTEND=noninteractive
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Verify Docker image
              run: |
                  echo "=== Docker 映像檢查 ==="
                  docker images test/beststore:latest
                  echo ""
                  echo "=== 映像詳細資訊 ==="
                  docker inspect test/beststore:latest | grep -E "(Created|Size|Architecture)"
